1--
SELECT NAME, DATETIME
FROM(SELECT I.NAME AS NAME, I.DATETIME AS DATETIME
    FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NULL
    ORDER BY I.DATETIME)
WHERE rownum <= 3;

2--
SELECT I.NAME, I.DATETIME
FROMANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME FETCH FIRST 3 ROW ONLY;
